from sqlalchemy.orm import Session
from app.models.patient import Patient as PatientModel
from app.schemas.patient import PatientCreate

# CREATE: Add a new patient to the database
def create_patient(db: Session, patient: PatientCreate):
    # Convert the Pydantic schema data into a SQLAlchemy model
    db_patient = PatientModel(**patient.model_dump())
    db.add(db_patient)
    db.commit()
    db.refresh(db_patient) # This gets the new ID generated by the database
    return db_patient

# READ: Get a single patient by their ID
def get_patient(db: Session, patient_id: int):
    return db.query(PatientModel).filter(PatientModel.id == patient_id).first()

# READ: Get a list of all patients
def get_patients(db: Session, skip: int = 0, limit: int = 100):
    return db.query(PatientModel).offset(skip).limit(limit).all()

# DELETE: Remove a patient from the database
def delete_patient(db: Session, patient_id: int):
    db_patient = db.query(PatientModel).filter(PatientModel.id == patient_id).first()
    if db_patient:
        db.delete(db_patient)
        db.commit()
    return db_patient